jobs:
  - name: old-min-sh
    type: runSh
    steps:
      - TASK:
        - script: echo "hello world"
      
  - name: new-min-sh-windows
    type: runSh
    runtime:
      nodePool: default_node_pool
      container: false
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"


########## flags from slackbot

  - name: f1-f2
    type: runSh
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
    flags:
      - f1
      - f2
      
  - name: f2-f3
    type: runSh
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
    flags:
      - f2
      - f3
      
  - name: f1-f3
    type: runSh
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
    flags:
      - f1
      - f3
