jobs:
  - name: old-min-sh
    type: runSh
    steps:
      - TASK:
        - script: echo "hello world"
      
  - name: new-min-sh-windows
    type: runSh
    runtime:
      nodePool: default_node_pool
      container: false
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"


########## flags from slackbot
  - name: local-ci_runCI
    type: runCI
    steps:
      - IN: local-ci_ciRepo
    flags:
      - f1

  - name: f1-f2
    type: runSh
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
            - echo "JOB_TRIGGERED_BY_NAME = $JOB_TRIGGERED_BY_NAME"
            - echo "JOB_TRIGGERED_BY_ID = $JOB_TRIGGERED_BY_ID"
            - echo "JOB_TRIGGERED_BY_USER = $JOB_TRIGGERED_BY_USER"
    flags:
      - f1
      - f2
      
  - name: temp
    type: runSh
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
            - echo "JOB_TRIGGERED_BY_NAME = $JOB_TRIGGERED_BY_NAME"
            - echo "JOB_TRIGGERED_BY_ID = $JOB_TRIGGERED_BY_ID"
            - echo "JOB_TRIGGERED_BY_USER = $JOB_TRIGGERED_BY_USER"
      
  - name: f2-f3
    type: runSh
    steps:
      - IN: temp
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
            - echo "JOB_TRIGGERED_BY_NAME = $JOB_TRIGGERED_BY_NAME"
            - echo "JOB_TRIGGERED_BY_ID = $JOB_TRIGGERED_BY_ID"
            - echo "JOB_TRIGGERED_BY_USER = $JOB_TRIGGERED_BY_USER"
    flags:
      - f2
      - f3
      
  - name: f1-f3
    type: runSh
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
            - echo "JOB_TRIGGERED_BY_NAME = $JOB_TRIGGERED_BY_NAME"
            - echo "JOB_TRIGGERED_BY_ID = $JOB_TRIGGERED_BY_ID"
            - echo "JOB_TRIGGERED_BY_USER = $JOB_TRIGGERED_BY_USER"
    flags:
      - f1
      - f3
